language: php
php:
- 7.4
- 7.3
- 7.2
- 8.0
matrix:
  allow_failures:
  - php: 8.0
install:
- composer install
script: vendor/bin/phpunit  --coverage-clover build/logs/clover.xml
after_success:
- if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then travis_retry php vendor/bin/coveralls
  -v; fi
